version: '3'

volumes:
    mongodb_data_db:

services:
    gathio:
        build: .
        links:
         - mongo
        ports:
            - 3000:3000
    mongo:
        image: mongo:latest
        volumes:
            - mongodb_data_db:/data/db        